on: [workflow_dispatch]
name: Validate Schema
jobs:
  validate_chainjson:
    name: Validate edited chains.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate projects.json schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: projects.schema.json
          json_path_pattern: projects.json
